### ISSUE TITLE
Feature request: add new columns to the output

### ISSUE THREAD

**Issue by telezhnaya** [near-cli-rs/near-validator-cli-rs#13]
With 2.0.0 release, we have a new validator role: Chunk Validator https://github.com/near/nearcore/releases/tag/2.0.0
It becomes important to track num_produced_endorsements
Let's add 2 new columns to the output?
Providing the command to show the values I want to see in the output of near-validators

```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": "dontcare", "method": "validators", "params": [null]}' https://rpc.mainnet.near.org | jq '.result.current_validators[] | select(.account_id=="any_pool.poolv1.near") | {account_id, num_produced_endorsements, num_expected_endorsements, num_expected_blocks, num_expected_chunks, num_produced_blocks, num_produced_chunks}'
```

**Comment by FroVolod** [comment]
@telezhnaya Is this how you see the outcome of this command?
```
near-validator validators network-config mainnet now
```
![Screenshot 2024-08-15 at 21 48 08](https://github.com/user-attachments/assets/79dc335f-331a-478d-831e-29f1896cc348)
![Screenshot 2024-08-15 at 21 48 36](https://github.com/user-attachments/assets/80eb930a-09a8-46b7-a97d-7ca0a0acf60f)

**Comment by telezhnaya** [comment]
Yes, thank you!

May I ask you to fix the online percent formula as well? It can be done in a separate PR.

The correct logic is

If  num_expected_blocks > 0 or num_expected_chunks > 0, 
We should ignore endorsements completely
And we should take min(num_produced_blocks / num_expected_blocks, num_produced_chunks / num_expected_chunks) * 100

If both num_expected_blocks and num_expected_chunks are 0,
It's num_produced_endorsements / num_expected_endorsements * 100

**Comment by FroVolod** [comment]
> Yes, thank you!
> 
> May I ask you to fix the online percent formula as well? It can be done in a separate PR.
> 
> The correct logic is
> 
> If num_expected_blocks > 0 or num_expected_chunks > 0, We should ignore endorsements completely And we should take min(num_produced_blocks / num_expected_blocks, num_produced_chunks / num_expected_chunks) * 100
> 
> If both num_expected_blocks and num_expected_chunks are 0, It's num_produced_endorsements / num_expected_endorsements * 100

![Screenshot 2024-08-16 at 13 48 58](https://github.com/user-attachments/assets/bd3ac2f9-6fda-4436-a1ca-1bc7df35a2a2)
Is this additional validation required (can num_expected_endorsements = 0)?
What are the logical signs that the validator is not working?

In general, are there any possible cases of division by 0 that need to be taken into account?

**Comment by telezhnaya** [comment]
> Is this additional validation required

Yes.
Actually I think it will never be the case, but you should never trust anyone, any situation is possible 😄

**Comment by telezhnaya** [comment]
You can open the PR and add me as an additional reviewer

**Comment by FroVolod** [comment]
I cannot add you as an additional reviewer :(
https://github.com/near-cli-rs/near-validator-cli-rs/pull/15

**Comment by telezhnaya** [comment]
Reviewed, thank you for your work!
